### ISSUE TITLE
exited on signal 6 (core dumped)

### ISSUE THREAD

**Issue by jsm222** [cjd/mtpfs#1]
as root on freebsd-10.1 (in VirtualBox eg not usb 2.0)
mtpfs /mnt
Listing raw device(s)
Device 0 (VID=0fce and PID=0170) is a SONY ST21i Xperia Tipo MTP.
   Found 1 device(s):
   SONY: ST21i Xperia Tipo MTP (0fce:0170) @ bus 0, dev 2
Attempting to connect device
Android device detected, assigning default bug flags
Listing File Information on Device with name: (NULL)
dmeg (exited on signal 6 (core dumped))
#0  0x00000008025b16ca in thr_kill () from /lib/libc.so.7
#1  0x0000000802686149 in abort () from /lib/libc.so.7
#2  0x000000080139fa80 in g_thread_abort (status=1, function=0x8013fdaed "pthread_mutex_unlock") at gthread-posix.c:80
#3  0x000000080139faba in g_mutex_unlock (mutex=0x80401e7c0) at gthread-posix.c:236
#4  0x000000000040567a in mtpfs_getattr (path=0x80401ec00 "/", stbuf=0x7fffffbfdbf8) at mtpfs.c:919
#5  0x000000080082e475 in fuse_fs_getattr (fs=0x804096300, path=0x80401ec00 "/", buf=0x7fffffbfdbf8) at fuse.c:1596
#6  0x0000000800834b9f in fuse_lib_getattr (req=0x80404e400, ino=1, fi=0x0) at fuse.c:2734
#7  0x000000080083fd94 in do_getattr (req=0x80404e400, nodeid=1, inarg=0x8040eb028) at fuse_lowlevel.c:1044
#8  0x000000080083f3a5 in fuse_ll_process_buf (data=0x804064600, buf=0x7fffffbfdf58, ch=0x804016300) at fuse_lowlevel.c:2441
#9  0x00000008008444a0 in fuse_session_process_buf (se=0x8040632e0, buf=0x7fffffbfdf58, ch=0x804016300) at fuse_session.c:87
#10 0x000000080083c063 in fuse_do_work (data=0x804017cd0) at fuse_loop_mt.c:117
#11 0x00000008023284f5 in pthread_create () from /lib/libthr.so.3
#12 0x0000000000000000 in ?? ()

**Comment by cjd** [comment]
Should be fixed by commit from back in 2015
